Repository ironcore-dev/ironcore-in-a-box, pull requests merged in 2025-05, with the labels that each got.

#42 Document MacOS requirements
  README.md
Labels: documentation, enhancement, size/S

#44 Add information on podman on MacOS
  Makefile
  README.md
Labels: documentation, size/M

#43 Enhance MacOS related doc
  README.md
  docs/podman.md
Labels: documentation, enhancement, size/M
