Repository ironcore-dev/ironcore-in-a-box, pull requests merged in 2025-03, with the labels that each got.

#29 Adapt to metalbond spoofer changes
  base/metalbond-client/daemonset.yaml
  examples/machine/machine.yaml
Labels: enhancement, size/S

#32 Fix network setup for non standard docker networks
  Makefile
  hack/setup-network.sh
Labels: bug, size/S

#36 Document how to use examples with ironcore-in-a-box
  README.md
Labels: documentation, enhancement, size/XS
